# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(319, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(149, 200, 172);\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.pushButton_0_ = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_0_.setGeometry(QtCore.QRect(0, 329, 151, 71))
        self.pushButton_0_.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_0_.setObjectName("pushButton_0_")
        self.pushButton_ravno = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ravno.setGeometry(QtCore.QRect(159, 329, 141, 71))
        self.pushButton_ravno.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_ravno.setObjectName("pushButton_ravno")
        self.pushButton_7_ = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7_.setGeometry(QtCore.QRect(0, 220, 81, 61))
        self.pushButton_7_.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_7_.setObjectName("pushButton_7_")
        self.pushButton_8_ = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8_.setGeometry(QtCore.QRect(80, 220, 81, 61))
        self.pushButton_8_.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_8_.setObjectName("pushButton_8_")
        self.pushButton_9_ = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9_.setGeometry(QtCore.QRect(160, 220, 81, 61))
        self.pushButton_9_.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_9_.setObjectName("pushButton_9_")
        self.pushButton_5_ = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5_.setGeometry(QtCore.QRect(80, 160, 81, 61))
        self.pushButton_5_.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_5_.setObjectName("pushButton_5_")
        self.pushButton_4_ = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4_.setGeometry(QtCore.QRect(0, 160, 81, 61))
        self.pushButton_4_.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_4_.setObjectName("pushButton_4_")
        self.pushButton_6_ = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6_.setGeometry(QtCore.QRect(160, 160, 81, 61))
        self.pushButton_6_.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_6_.setObjectName("pushButton_6_")
        self.pushButton_2_ = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2_.setGeometry(QtCore.QRect(80, 100, 81, 61))
        self.pushButton_2_.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_2_.setObjectName("pushButton_2_")
        self.pushButton_1_ = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1_.setGeometry(QtCore.QRect(0, 100, 81, 61))
        self.pushButton_1_.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_1_.setObjectName("pushButton_1_")
        self.pushButton_3_ = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3_.setGeometry(QtCore.QRect(160, 100, 81, 61))
        self.pushButton_3_.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_3_.setObjectName("pushButton_3_")
        self.pushButton_plus = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_plus.setGeometry(QtCore.QRect(250, 90, 51, 51))
        self.pushButton_plus.setStyleSheet("alternate-background-color: rgb(85, 255, 127);")
        self.pushButton_plus.setObjectName("pushButton_plus")
        self.pushButton_minus = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_minus.setGeometry(QtCore.QRect(250, 140, 51, 51))
        self.pushButton_minus.setStyleSheet("alternate-background-color: rgb(85, 255, 127);")
        self.pushButton_minus.setObjectName("pushButton_minus")
        self.pushButton_umn = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_umn.setGeometry(QtCore.QRect(250, 190, 51, 51))
        self.pushButton_umn.setStyleSheet("alternate-background-color: rgb(85, 255, 127);")
        self.pushButton_umn.setObjectName("pushButton_umn")
        self.pushButton_razd = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_razd.setGeometry(QtCore.QRect(250, 240, 51, 51))
        self.pushButton_razd.setStyleSheet("alternate-background-color: rgb(85, 255, 127);")
        self.pushButton_razd.setObjectName("pushButton_razd")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_functions()

        self.is_equal = False

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Калькулятор"))
        self.label.setText(_translate("MainWindow", "0"))
        self.pushButton_0_.setText(_translate("MainWindow", "0"))
        self.pushButton_ravno.setText(_translate("MainWindow", "="))
        self.pushButton_7_.setText(_translate("MainWindow", "7"))
        self.pushButton_8_.setText(_translate("MainWindow", "8"))
        self.pushButton_9_.setText(_translate("MainWindow", "9"))
        self.pushButton_5_.setText(_translate("MainWindow", "5"))
        self.pushButton_4_.setText(_translate("MainWindow", "4"))
        self.pushButton_6_.setText(_translate("MainWindow", "6"))
        self.pushButton_2_.setText(_translate("MainWindow", "2"))
        self.pushButton_1_.setText(_translate("MainWindow", "1"))
        self.pushButton_3_.setText(_translate("MainWindow", "3"))
        self.pushButton_plus.setText(_translate("MainWindow", "+"))
        self.pushButton_minus.setText(_translate("MainWindow", "-"))
        self.pushButton_umn.setText(_translate("MainWindow", "*"))
        self.pushButton_razd.setText(_translate("MainWindow", "/"))


    def add_functions(self):
        self.pushButton_0_.clicked.connect(lambda: self.write_number(self.pushButton_0_.text()))
        self.pushButton_1_.clicked.connect(lambda: self.write_number(self.pushButton_1_.text()))
        self.pushButton_2_.clicked.connect(lambda: self.write_number(self.pushButton_2_.text()))
        self.pushButton_3_.clicked.connect(lambda: self.write_number(self.pushButton_3_.text()))
        self.pushButton_plus.clicked.connect(lambda: self.write_number(self.pushButton_plus.text()))
        self.pushButton_minus.clicked.connect(lambda: self.write_number(self.pushButton_minus.text()))

        self.pushButton_ravno.clicked.connect(lambda: self.results())

    def write_number(self, number):
        if self.label.text() == '0' or self.is_equal == True:
            self.label.setText(number)
            self.is_equal = False
        else:
            self.label.setText(self.label.text() + number)

    def results(self):
        if not self.is_equal:
            res = eval(self.label.text())
            self.label.setText("Result: " + str(res))
            self.is_equal = True
        else:
            error = QMessageBox()
            error.setWindowTitle('Erorrrrr')
            error.setText('Ypu dont do io')
            error.setIcon(QMessageBox.Warning)

            error.setStandardButtons(QMessageBox.Reset|QMessageBox.Ok|QMessageBox.Cancel)
            error.setDefaultButton(QMessageBox.Ok)
            error.setInformativeText('Two do no can')
            error.setDetailedText('sajfljasgljalsg')
            error.buttonClicked.connect(self.popup_action)
            error.exec_()



    def popup_action(self, btn):
        if btn.text() == "Ok":
            print('OOOOK')
        elif btn.text() == 'Reset':
            self.label.setText("")
            self.is_equal = False
        else:
            print('11111')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
